### PR TITLE
pg: fix timetz with timezone

### LINKED ISSUE #2691: Cant CDC from postgres to clickhouse a table with tz
Hi, thanks for the product!

Im trying to mirror a table from postgres 14 to clickhouse, here is table DDL I want to mirror

```sql
create table workers_schedule
(
    id         serial
        primary key,
    start_time time with time zone not null,
    end_time   time with time zone not null,
    worker_id  uuid                not null
        references workers
            on delete cascade,
    week_day   varchar(2)
);
```

when enabled, I see such logs in flow-worker

```
{
    "time": "2025-03-11T12:05:23.602098349Z",
    "level": "ERROR",
    "msg": "[pg_query_executor] failed to process fetched rows",
    "Namespace": "default",
    "TaskQueue": "peer-flow-task-queue",
    "WorkerID": "1@peer-db-flow-worker-d987f744-4m964@",
    "ActivityID": "5",
    "ActivityType": "ReplicateQRepPartitions",
    "Attempt": 1,
    "WorkflowType": "QRepPartitionWorkflow",
    "WorkflowID": "qrep-part-clone_workers_workers_schedule_01958517_f7f2_7503_8113_4069bf075d54-35cf9b38-1609-4e74-97f5-5360793ad938",
    "RunID": "01958518-6346-76ef-8bb8-ac5dfbbc7f30",
    "flowName": "clone_workers_workers_schedule_01958517_f7f2_7503_8113_4069bf075d54",
    "x-peerdb-flow-metadata":
    {
        "flow_name": "workers",
        "source":
        {
            "name": "workers",
            "type": 3
        },
        "destination":
        {
            "name": "clickhouse",
            "type": 8
        },
        "status": 4
    },
    "x-peerdb-additional-metadata":
    {
        "Operation": 0
    },
    "partitionId": "c18efd06-ec22-4786-acae-d1e92d0cc72b",
    "error": "failed to process rows: failed to map row to QRecord: failed to parse field: failed to parse time: parsing time \"09:25:00+03\" as \"15:04:05.999999-0700\": cannot parse \"+03\" as \"-0700\"",
    "deploymentUid": ""
}
```

The data in this table looks valid
```sql
INSERT INTO public.workers_schedule (id, start_time, end_time, worker_id, week_day) VALUES (1863, '09:25:00 +03:00', '19:25:00 +03:00', '12354d78-a864-471f-9827-e89c43aadebd', 'MO');
INSERT INTO public.workers_schedule (id, start_time, end_time, worker_id, week_day) VALUES (1864, '09:25:00 +03:00', '19:25:00 +03:00', '12354d78-a864-471f-9827-e89c43aadebd', 'TU');
INSERT INTO public.workers_schedule (id, start_time, end_time, worker_id, week_day) VALUES (1865, '09:25:00 +03:00', '19:25:00 +03:00', '12354d78-a864-471f-9827-e89c43aadebd', 'WE');
```

How to overcome this issue?

### PR DESCRIPTION
**Pull request by serprex**
fixes #2691

### CODE REVIEW

File: flow/connectors/postgres/qvalue_convert.go [hunk 1]
```diff
@@ -387,7 +387,7 @@ func parseFieldFromQValueKind(qvalueKind qvalue.QValueKind, value any) (qvalue.Q
 		timeVal = strings.Replace(timeVal, "24:00:00.000000", "23:59:59.999999", 1)
 		// edge case, Postgres prints +0000 as +00
 		timeVal = strings.Replace(timeVal, "+00", "+0000", 1)
```
Comment (serprex) [inline flow/connectors/postgres/qvalue_convert.go:389]: this will break if postgres sends `+0000` ever, ideally it'd check for `\+00([^\d]|$)`

Comment (evstratbg) [reply flow/connectors/postgres/qvalue_convert.go:389]: There are some records like this in my table

INSERT INTO public.workers_schedule (id, start_time, end_time, worker_id, week_day) VALUES (5919, '08:00:00 +00:00', '21:00:00 +00:00', '2c3e2124-3ca1-487f-b4ca-543874577c67', 'TH');

Comment (serprex) [reply flow/connectors/postgres/qvalue_convert.go:389]: Good to know, tho this code only needs to accept what postgres would output, rather than what it accepts as input

Will address this gap still

**Review by Amogh-Bharadwaj — APPROVED** [review]
